// Turns the originals in /photos into small, web-ready WebP files in /public/images,
// and writes /src/data/photos.js with each photo's size + a tiny blurred placeholder.
// Run again after adding or swapping photos:  npm run photos
import sharp from 'sharp';
import exifr from 'exifr';
import fs from 'node:fs/promises';
import path from 'node:path';

const SRC = 'photos';
const OUT_IMG = 'public/images';
const OUT_JS = 'src/data/photos.js';
const WIDTHS = [480, 960, 1440];

async function walk(dir) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files = await Promise.all(entries.map((e) => {
    const p = path.join(dir, e.name);
    return e.isDirectory() ? walk(p) : p;
  }));
  return files.flat();
}

const slugify = (name) => path.parse(name).name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

await fs.mkdir(OUT_IMG, { recursive: true });
const files = (await walk(SRC)).filter((f) => /\.(jpe?g|png|webp|heic)$/i.test(f));
const manifest = {};

for (const file of files) {
  const slug = slugify(file);
  const base = sharp(file).rotate(); // respect EXIF orientation
  const { width, height } = await base.clone().toBuffer({ resolveWithObject: true }).then((r) => r.info);

  const srcset = [];
  for (const w of WIDTHS) {
    if (w > width && w !== WIDTHS[0]) continue;
    const out = `${slug}-${w}.webp`;
    await base.clone().resize({ width: Math.min(w, width) }).webp({ quality: 78 }).toFile(path.join(OUT_IMG, out));
    srcset.push([`images/${out}`, Math.min(w, width)]);
  }

  const blur = await base.clone().resize(16).webp({ quality: 40 }).toBuffer();
  let date = null;
  try { date = (await exifr.parse(file, ['DateTimeOriginal']))?.DateTimeOriginal ?? null; } catch {}

  manifest[path.basename(file)] = {
    w: width,
    h: height,
    srcset,
    blur: `data:image/webp;base64,${blur.toString('base64')}`,
    date: date ? new Date(date).toISOString().slice(0, 10) : null,
  };
  console.log(`✓ ${path.basename(file)} → ${srcset.length} sizes`);
}

await fs.writeFile(
  OUT_JS,
  `// AUTO-GENERATED by scripts/optimize-photos.mjs — don't edit by hand.\nexport const PHOTOS =${JSON.stringify(manifest, null, 2)};\n`
);
console.log(`\nWrote ${Object.keys(manifest).length} photos to ${OUT_IMG} and ${OUT_JS}`);
